languageCode = "ja-JP"
title = "Play2 and ScalikeJDBC Hands-on"
baseURL = "http://takezoe.github.io/play2-hands-on/"
theme = "hugo_theme_robust"
metadataformat = "yaml"
canonifyurls = true
uglyurls = true
publishDir = "docs"
copyright = "BizReach, Inc (Translated to English by Naoki Takezoe)"